In [1]:
#load data
import pickle as pkl
import pandas as pd
f1 = open('all_metrics_data_12h.pkl', 'rb')
label_data = pkl.load(f1)
f2 = open('related_metrics_12h.pkl', 'rb')
txn_failure_correlation = pkl.load(f2)
label_data

time  label  txn_fail_num   CPU Busy  Sys Load (5m avg)  \
0    2021-06-17 09:33:00      0           0.0  11.634746              35.25   
1    2021-06-17 09:33:15      0           0.0  13.043220              38.50   
2    2021-06-17 09:33:30      0           0.0  14.499153              40.75   
3    2021-06-17 09:33:45      0           0.0  15.869492              45.25   
4    2021-06-17 09:34:00      0           0.0  16.991525              60.75   
...                  ...    ...           ...        ...                ...   
3232 2021-06-17 23:01:00      1         130.0  23.907627              85.25   
3233 2021-06-17 23:01:15      0           0.0  22.467797              82.75   
3234 2021-06-17 23:01:30      0           0.0  21.074576              78.50   
3235 2021-06-17 23:01:45      0           0.0  20.477119              75.25   
3236 2021-06-17 23:02:00      0           0.0  19.132203              71.75   

      Sys Load (15m avg)      RAM Used  SWAP Used  CPU Cores        Uptime  \
0                  36.50  1.761575e+09        0.0        4.0  1.347665e+07   
1                  37.50  1.824432e+09        0.0        4.0  1.347667e+07   
2                  38.25  1.876513e+09        0.0        4.0  1.347668e+07   
3                  39.75  1.886544e+09        0.0        4.0  1.347670e+07   
4                  45.00  1.889354e+09        0.0        4.0  1.347671e+07   
...                  ...           ...        ...        ...           ...   
3232              144.25  2.379063e+09        0.0        4.0  1.352513e+07   
3233              142.50  2.384826e+09        0.0        4.0  1.352515e+07   
3234              140.25  2.390565e+09        0.0        4.0  1.352516e+07   
3235              138.00  2.391216e+09        0.0        4.0  1.352518e+07   
3236              136.00  2.393104e+09        0.0        4.0  1.352519e+07   

      ...  InErrs - Segments received in error (e.g., bad TCP checksums)  \
0     ...                                                0.0               
1     ...                                                0.0               
2     ...                                                0.0               
3     ...                                                0.0               
4     ...                                                0.0               
...   ...                                                ...               
3232  ...                                                0.0               
3233  ...                                                0.0               
3234  ...                                                0.0               
3235  ...                                                0.0               
3236  ...                                                0.0               

      CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT  \
0                                                   1.0                                              
1                                                   1.0                                              
2                                                   1.0                                              
3                                                   1.0                                              
4                                                   1.0                                              
...                                                 ...                                              
3232                                                1.0                                              
3233                                                1.0                                              
3234                                                1.0                                              
3235                                                1.0                                              
3236                                                1.0                                            

In [2]:
label_data.label.tolist()[71:76]

[0, 0, 0, 1, 1]

In [3]:
outlier_fraction = len(label_data[label_data['label'] == 1])/len(label_data)
outlier_fraction

0.28143342601173926

## Normalize

In [4]:
#normalize data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
normalized_data = pd.DataFrame(scaler.fit_transform(label_data.drop(['time'], axis=1)))
normalized_data.columns = label_data.columns[1:]
normalized_label_data = pd.merge(label_data.time, normalized_data, left_index=True, right_index=True, how='left')
normalized_label_data

time  label  txn_fail_num  CPU Busy  Sys Load (5m avg)  \
0    2021-06-17 09:33:00    0.0      0.978715  0.078088           0.078054   
1    2021-06-17 09:33:15    0.0      0.978715  0.093869           0.085407   
2    2021-06-17 09:33:30    0.0      0.978715  0.110182           0.090498   
3    2021-06-17 09:33:45    0.0      0.978715  0.125535           0.100679   
4    2021-06-17 09:34:00    0.0      0.978715  0.138107           0.135747   
...                  ...    ...           ...       ...                ...   
3232 2021-06-17 23:01:00    1.0      0.981353  0.215597           0.191176   
3233 2021-06-17 23:01:15    0.0      0.978715  0.199464           0.185520   
3234 2021-06-17 23:01:30    0.0      0.978715  0.183854           0.175905   
3235 2021-06-17 23:01:45    0.0      0.978715  0.177160           0.168552   
3236 2021-06-17 23:02:00    0.0      0.978715  0.162091           0.160633   

      Sys Load (15m avg)  RAM Used  SWAP Used  CPU Cores    Uptime  ...  \
0               0.104827  0.266319        0.0        0.0  0.000000  ...   
1               0.107843  0.288054        0.0        0.0  0.000309  ...   
2               0.110106  0.306063        0.0        0.0  0.000618  ...   
3               0.114630  0.309532        0.0        0.0  0.000927  ...   
4               0.130468  0.310503        0.0        0.0  0.001236  ...   
...                  ...       ...        ...        ...       ...  ...   
3232            0.429864  0.479838        0.0        0.0  0.998764  ...   
3233            0.424585  0.481831        0.0        0.0  0.999073  ...   
3234            0.417798  0.483815        0.0        0.0  0.999382  ...   
3235            0.411011  0.484041        0.0        0.0  0.999691  ...   
3236            0.404977  0.484694        0.0        0.0  1.000000  ...   

      InErrs - Segments received in error (e.g., bad TCP checksums)  \
0                                                   0.0               
1                                                   0.0               
2                                                   0.0               
3                                                   0.0               
4                                                   0.0               
...                                                 ...               
3232                                                0.0               
3233                                                0.0               
3234                                                0.0               
3235                                                0.0               
3236                                                0.0               

      CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT  \
0                                                   0.0                                              
1                                                   0.0                                              
2                                                   0.0                                              
3                                                   0.0                                              
4                                                   0.0                                              
...                                                 ...                                              
3232                                                0.0                                              
3233                                                0.0                                              
3234                                                0.0                                              
3235                                                0.0                                              
3236                                                0.0                                              

      SyncookiesFailed - Invalid SYN cookies received  \
0                                              

In [5]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA

# all, cor, pca
data_feature = 'pca' 
if data_feature == 'all':
    related_label_data = normalized_label_data.drop(['time', 'label', 'txn_fail_num'], axis=1)
if data_feature == 'cor':
    related_metrics_name = txn_failure_correlation.index
    related_label_data = normalized_label_data[related_metrics_name]
if data_feature == 'pca':
    pca = PCA(n_components=15)
    related_label_data = pca.fit_transform(normalized_label_data.drop(['time', 'label', 'txn_fail_num'], axis=1))
    related_label_data = pd.DataFrame(related_label_data)
related_label_data

0         1         2         3         4         5         6   \
0    -0.628476 -0.629605  2.652079  1.099140  1.614239  0.153452  1.368393   
1    -0.514359 -0.683051  2.611074  1.078258  1.602711  0.152961  1.385539   
2    -0.399568 -0.739660  2.566976  1.074209  1.616582  0.135461  1.421067   
3    -0.295562 -0.772949  2.531558  1.017152  1.603817  0.119985  1.444848   
4    -0.185498 -0.796569  2.492199  0.985679  1.610759  0.126438  1.419630   
...        ...       ...       ...       ...       ...       ...       ...   
3232 -0.124648 -0.544708  0.606105 -1.065107  0.380935  0.489242  0.928312   
3233 -0.258835 -0.491280  0.640420 -1.033738  0.350921  0.537932  0.938297   
3234 -0.347211 -0.456669  0.664849 -0.987720  0.345878  0.552619  0.925334   
3235 -0.385334 -0.466455  0.665397 -0.975486  0.192788  0.554839  0.808182   
3236 -0.459990 -0.462797  0.638574 -0.942256 -0.110656  0.500622  0.393414   

            7         8         9         10        11        12        13  \
0     0.081433  0.224312 -0.088355  0.488828  0.571520  0.471970 -0.373295   
1     0.089866  0.205290 -0.088692  0.487516  0.583965  0.465289 -0.339474   
2     0.071215  0.204005 -0.020981  0.467458  0.559282  0.375996 -0.368413   
3     0.116725  0.173576 -0.074490  0.477224  0.520184  0.303820 -0.328113   
4     0.137401  0.154677 -0.094233  0.484264  0.519654  0.302773 -0.289640   
...        ...       ...       ...       ...       ...       ...       ...   
3232 -0.012139 -0.320114  0.306996  0.271058  0.244903 -0.286942  0.125715   
3233  0.008353 -0.306704  0.285673  0.257760  0.257615 -0.283785  0.123319   
3234 -0.023657 -0.290637  0.327189  0.255613  0.293181 -0.217829  0.099298   
3235 -0.017850 -0.336696  0.316459  0.167274  0.180101 -0.221200  0.100532   
3236  0.034284 -0.418428  0.247493  0.036486  0.151743 -0.292909  0.023610   

            14  
0     0.276518  
1     0.246336  
2     0.182257  
3     0.200747  
4     0.190934  
...        ...  
3232 -0.146805  
3233 -0.143012  
3234 -0.144947  
3235 -0.122096  
3236 -0.140004  

[3237 rows x 15 columns]

## Ensemble

In [6]:
from __future__ import division
from __future__ import print_function

import os
import sys
from time import time

# temporary solution for relative imports in case pyod is not installed
# if pyod is installed, no need to use the following line
sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname("__file__"), '..')))
# supress warnings for clean output
import warnings

warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from scipy.io import loadmat

from pyod.models.iforest import IForest
from pyod.models.knn import KNN
from pyod.models.lof import LOF
from pyod.models.ocsvm import OCSVM
from pyod.models.pca import PCA

from pyod.utils.utility import standardizer
from pyod.utils.utility import precision_n_scores
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn import metrics

import numpy as np
from sklearn.model_selection import train_test_split
from scipy.io import loadmat

from pyod.models.combination import aom, moa, average, maximization, majority_vote
from pyod.utils.data import generate_data
from pyod.utils.data import evaluate_print

In [7]:
def pred_labels(y_test, test_scores):
    fpr, tpr, thresholds = roc_curve(y_test, test_scores)
    cutoff = thresholds[np.argmax(tpr - fpr)]
    pred_label = []
    for each in test_scores:
        if each > cutoff:
            pred_label.append(1)
        else:
            pred_label.append(0)    
    return pred_label

In [8]:
from sklearn.metrics.cluster import normalized_mutual_info_score
def MI_weights(test_scores):
    mi_matrix = np.zeros(shape=(4,4))
    for i in range(4):
        for j in range(4):
            base_a = test_scores[:,i]
            base_b = test_scores[:,j]
            mi_matrix[i][j] = normalized_mutual_info_score(base_a, base_b) 
    #mi_avg = 1/((sum(mi_matrix) - 1)/3)
    mi_avg = (sum(mi_matrix) - 1)/3
    weights = mi_avg/sum(mi_avg)
    estimator_weights = weights.reshape(1,4)
#     print('********')
#     print(mi_matrix)
#     print(mi_avg)
#     print(weights)
    print(estimator_weights)
#     print('--------')
    return estimator_weights

In [9]:
def cal_eval(label, pred_label, scores):
    pr = round(metrics.precision_score(label, pred_label, average='macro'), ndigits=4)
    re = round(metrics.recall_score(label, pred_label, average='macro'), ndigits=4)
    f1 = round(metrics.f1_score(label, pred_label, average='macro'), ndigits=4)
    roc = round(roc_auc_score(label, scores), ndigits=4)
    return pr,re,f1,roc

In [10]:
labels_df = pd.DataFrame(normalized_label_data[normalized_label_data.columns[:3]]) 
X_train = related_label_data
y_train = labels_df['label']
X_test = related_label_data
y_test = labels_df['label']
outliers_fraction = np.count_nonzero(y_train) / len(y_train)

In [11]:
#Ensemble methods
def ensemble_models():
    df_columns = ['Precision', 'Recall', 'F1 score', 'AUC', 'Train time', 'Test time']
    enm_avg_df = pd.DataFrame(columns=df_columns)
    enm_max_df = pd.DataFrame(columns=df_columns)
    enm_w_avg_df = pd.DataFrame(columns=df_columns)

    random_state = np.random.RandomState(42)
    classifiers = {
            'Isolation Forest': IForest(contamination=outliers_fraction,
                                        random_state=random_state),
            'K Nearest Neighbors (KNN)': KNN(contamination=outliers_fraction),
            'Local Outlier Factor (LOF)': LOF(
                contamination=outliers_fraction),
            'One-class SVM (OCSVM)': OCSVM(contamination=outliers_fraction)
        }

    n_clf = len(classifiers)
    train_scores = np.zeros([X_train.shape[0], n_clf])
    test_scores = np.zeros([X_test.shape[0], n_clf])
    p_labels = np.zeros([X_test.shape[0], n_clf])
    i = 0
    train_duration = 0
    test_duration = 0
    for clf_name, clf in classifiers.items():
        t0 = time()
        clf.fit(X_train)
        t1 = time()
        test_sccore = clf.decision_function(X_test)
        t_t = time()
        test_mean_score = np.nanmean(test_scores)
        test_scores[np.isnan(test_scores)] = test_mean_score
        test_scores[:, i] = test_sccore
        p_labels[:, i] = pred_labels(y_test, test_sccore)
        i += 1
        print('Base detector %i is fitted for prediction' % i)
        train_duration += round(t1 - t0, ndigits=4)
        test_duration += round(t_t - t1, ndigits=4)
        
    #print(test_scores[71:76,:])

    # standardize test score
    test_scores_norm = standardizer(test_scores)
    
    print(np.round(test_scores_norm[71:76,:], decimals=2))

    # Combination by average
    t2 = time()
    y_by_average = average(test_scores_norm)
    t3 = time()
    evaluate_print('Combination by Average', y_test, y_by_average)
    pred_label = pred_labels(y_test, y_by_average)
    pr_avg, re_avg, f1_avg, roc_avg = cal_eval(y_test, pred_label, y_by_average)
    train_time_avg = round(train_duration+t3-t2, ndigits=4)
    test_time_avg = round(test_duration+t3-t2, ndigits=4)

    enm_avg = pd.DataFrame([pr_avg, re_avg, f1_avg, roc_avg, train_time_avg, test_time_avg]).transpose()
    enm_avg.columns = df_columns
    enm_avg_df = pd.concat([enm_avg_df, enm_avg], axis=0)
    
    print(np.round(y_by_average[71:76], decimals=2))

    # Combination by max
    t4 = time()
    y_by_maximization = maximization(test_scores_norm)
    t5 = time()
    evaluate_print('Combination by Maximization', y_test, y_by_maximization)
    pred_label = pred_labels(y_test, y_by_maximization)
    pr_max, re_max, f1_max, roc_max = cal_eval(y_test, pred_label, y_by_maximization)
    train_time_max = round(train_duration+t5-t4, ndigits=4)
    test_time_max = round(test_duration+t5-t4, ndigits=4)

    enm_max = pd.DataFrame([pr_max, re_max, f1_max, roc_max, train_time_max, test_time_max]).transpose()
    enm_max.columns = df_columns
    enm_max_df = pd.concat([enm_max_df, enm_max], axis=0)
    
    print(np.round(y_by_maximization[71:76],decimals=2))
    
    # Combination by weighted average
    t6 = time()
    pred_label_0 = pred_labels(y_test, test_scores_norm[:,0])
    pred_label_1 = pred_labels(y_test, test_scores_norm[:,1]) 
    pred_label_2 = pred_labels(y_test, test_scores_norm[:,2]) 
    pred_label_3 = pred_labels(y_test, test_scores_norm[:,3]) 
    pred_label_ = np.array((pred_label_0, pred_label_1, pred_label_2, pred_label_3)).T
    estimator_weights = MI_weights(pred_label_)
    #estimator_weights = MI_weights(test_scores_norm)
    y_by_w_average = average(test_scores_norm, estimator_weights)
    t7 = time()
    evaluate_print('Combination by weighted Average', y_test, y_by_w_average)
    pred_label = pred_labels(y_test, y_by_w_average)
    pr_w_avg, re_w_avg, f1_w_avg, roc_w_avg = cal_eval(y_test, pred_label, y_by_w_average)
    train_time_w_avg = round(train_duration+t7-t6, ndigits=4)
    test_time_w_avg = round(test_duration+t7-t6, ndigits=4)

    enm_w_avg = pd.DataFrame([pr_w_avg, re_w_avg, f1_w_avg, roc_w_avg, train_time_w_avg, test_time_w_avg]).transpose()
    enm_w_avg.columns = df_columns 
    enm_w_avg_df = pd.concat([enm_w_avg_df, enm_w_avg], axis=0)
    
#     print(np.round(estimator_weights[71:76], decimals=2))
#     print(np.round(y_by_w_average[71:76], decimals=2))
    
    return enm_avg_df, enm_max_df, enm_w_avg_df

In [12]:
a = [1,2,3]
b = [2,3,2]
c = np.array((a,b)).T
c

array([[1, 2],
       [2, 3],
       [3, 2]])

In [13]:
df_columns = ['Precision', 'Recall', 'F1 score', 'AUC', 'Train time', 'Test time']

t_enm_avg_df = pd.DataFrame(columns=df_columns)
t_enm_max_df = pd.DataFrame(columns=df_columns)
t_enm_w_avg_df = pd.DataFrame(columns=df_columns)

for i in range(10):
    print(i)
    enm_avg, enm_max, env_w_avg = ensemble_models()
    t_enm_avg_df = pd.concat([t_enm_avg_df, enm_avg], axis=0, ignore_index=True)
    t_enm_max_df = pd.concat([t_enm_max_df, enm_max], axis=0, ignore_index=True)
    t_enm_w_avg_df = pd.concat([t_enm_w_avg_df, env_w_avg], axis=0, ignore_index=True)

0
Base detector 1 is fitted for prediction
Base detector 2 is fitted for prediction
Base detector 3 is fitted for prediction
Base detector 4 is fitted for prediction
[[ 0.16 -0.1   0.23  0.75]
 [ 0.42  0.72  1.2   0.74]
 [ 1.83  3.35  1.54  1.07]
 [ 1.44  2.59  3.69  0.8 ]
 [ 1.5   2.11  0.56  0.7 ]]
Combination by Average ROC:0.8639, precision @ rank n:0.6915
[0.26 0.77 1.95 2.13 1.22]
Combination by Maximization ROC:0.8499, precision @ rank n:0.6389
[0.75 1.2  3.35 3.69 2.11]
[[0.39234921 0.2858296  0.03837507 0.28344613]]
Combination by weighted Average ROC:0.8764, precision @ rank n:0.7168
1
Base detector 1 is fitted for prediction
Base detector 2 is fitted for prediction
Base detector 3 is fitted for prediction
Base detector 4 is fitted for prediction
[[ 0.16 -0.1   0.23  0.75]
 [ 0.42  0.72  1.2   0.74]
 [ 1.83  3.35  1.54  1.07]
 [ 1.44  2.59  3.69  0.8 ]
 [ 1.5   2.11  0.56  0.7 ]]
Combination by Average ROC:0.8639, precision @ rank n:0.6915
[0.26 0.77 1.95 2.13 1.22]
Combinati

In [14]:
print('Ensemble average')
metrics = ['Precision', 'Recall', 'F1 score', 'AUC', 'Train time', 'Test time']
mean_avg = []
std_avg = []
for each in metrics:
    mean_avg.append(round(t_enm_avg_df[each].mean(), ndigits=4))
    std_avg.append(round(t_enm_avg_df[each].std(), ndigits=4))
print(mean_avg)
print(std_avg)
t_enm_avg_df

Ensemble average
[0.7847, 0.8428, 0.7941, 0.8639, 1.1413, 0.7847]
[0.0, 0.0, 0.0, 0.0, 0.0301, 0.0215]


Precision  Recall  F1 score     AUC  Train time  Test time
0     0.7847  0.8428    0.7941  0.8639      1.2021     0.8123
1     0.7847  0.8428    0.7941  0.8639      1.1778     0.8082
2     0.7847  0.8428    0.7941  0.8639      1.1654     0.8035
3     0.7847  0.8428    0.7941  0.8639      1.1110     0.7719
4     0.7847  0.8428    0.7941  0.8639      1.1290     0.7686
5     0.7847  0.8428    0.7941  0.8639      1.1201     0.7632
6     0.7847  0.8428    0.7941  0.8639      1.1178     0.7723
7     0.7847  0.8428    0.7941  0.8639      1.1325     0.7653
8     0.7847  0.8428    0.7941  0.8639      1.1227     0.7687
9     0.7847  0.8428    0.7941  0.8639      1.1342     0.8134

In [15]:
print('Ensemble max')
metrics = ['Precision', 'Recall', 'F1 score', 'AUC', 'Train time', 'Test time']
mean_max = []
std_max = []
for each in metrics:
    mean_max.append(round(t_enm_max_df[each].mean(), ndigits=4))
    std_max.append(round(t_enm_max_df[each].std(), ndigits=4))
print(mean_max)
print(std_max)
t_enm_max_df

Ensemble max
[0.7808, 0.8372, 0.7905, 0.8499, 1.1411, 0.7846]
[0.0, 0.0, 0.0, 0.0, 0.0301, 0.0215]


Precision  Recall  F1 score     AUC  Train time  Test time
0     0.7808  0.8372    0.7905  0.8499      1.2021     0.8123
1     0.7808  0.8372    0.7905  0.8499      1.1777     0.8081
2     0.7808  0.8372    0.7905  0.8499      1.1650     0.8031
3     0.7808  0.8372    0.7905  0.8499      1.1112     0.7721
4     0.7808  0.8372    0.7905  0.8499      1.1288     0.7684
5     0.7808  0.8372    0.7905  0.8499      1.1200     0.7631
6     0.7808  0.8372    0.7905  0.8499      1.1178     0.7723
7     0.7808  0.8372    0.7905  0.8499      1.1323     0.7651
8     0.7808  0.8372    0.7905  0.8499      1.1222     0.7682
9     0.7808  0.8372    0.7905  0.8499      1.1341     0.8133

In [16]:
print('Ensemble weighted avg')
metrics = ['Precision', 'Recall', 'F1 score', 'AUC', 'Train time', 'Test time']
mean_w_avg = []
std_w_avg = []
for each in metrics:
    mean_w_avg.append(round(t_enm_w_avg_df[each].mean(), ndigits=4))
    std_w_avg.append(round(t_enm_w_avg_df[each].std(), ndigits=4))
print(mean_w_avg)
print(std_w_avg)
t_enm_w_avg_df

Ensemble weighted avg
[0.8011, 0.8535, 0.8148, 0.8764, 1.1696, 0.813]
[0.0, 0.0, 0.0, 0.0, 0.0311, 0.0222]


Precision  Recall  F1 score     AUC  Train time  Test time
0     0.8011  0.8535    0.8148  0.8764      1.2334     0.8436
1     0.8011  0.8535    0.8148  0.8764      1.2074     0.8378
2     0.8011  0.8535    0.8148  0.8764      1.1934     0.8315
3     0.8011  0.8535    0.8148  0.8764      1.1398     0.8007
4     0.8011  0.8535    0.8148  0.8764      1.1561     0.7957
5     0.8011  0.8535    0.8148  0.8764      1.1483     0.7914
6     0.8011  0.8535    0.8148  0.8764      1.1459     0.8004
7     0.8011  0.8535    0.8148  0.8764      1.1600     0.7928
8     0.8011  0.8535    0.8148  0.8764      1.1497     0.7957
9     0.8011  0.8535    0.8148  0.8764      1.1616     0.8408

In [17]:
from sklearn.metrics.cluster import normalized_mutual_info_score
a = [1,0,0,0,1]
b = [0,0,0,1,1]
normalized_mutual_info_score(a,b)

0.020570659450692717

In [18]:
n = 5
n_0_a = 4
n_1_a = 1
n_0_b = 3
n_1_b = 2
n_0_ab = 3
n_1_ab = 1

In [19]:
np.log((n*(n_0_b-n_0_ab))/(n_1_a*n_0_b))

-inf

In [20]:
import numpy as np
#I_ab = n_0_ab * np.log((n*n_0_ab)/(n_0_a*n_0_b)) + (n_0_a-n_0_ab)*np.log((n*(n_0_a-n_0_ab))/(n_0_a*n_1_b)) + (n_0_b-n_0_ab)*np.log((n*(n_0_b-n_0_ab))/(n_1_a*n_0_b)) + n_1_ab * np.log((n*n_1_ab)/(n_1_a*n_1_b))
I_ab = n_0_ab * np.log((n*n_0_ab)/(n_0_a*n_0_b)) + (n_0_a-n_0_ab)*np.log((n*(n_0_a-n_0_ab))/(n_0_a*n_1_b)) + 0 + n_1_ab * np.log((n*n_1_ab)/(n_1_a*n_1_b))
I_ab

1.115717756571049

In [21]:
P_ab = I_ab/np.sqrt((n_0_a*np.log(n_0_a/n)+n_1_a*np.log(n_1_a/n))*(n_0_b*np.log(n_0_b/n)+n_1_b*np.log(n_1_b/n)))
P_ab

0.38451504912796675